// A2BM C     110
// DO NOT EDIT THIS FILE

waitUntil {!(isNull player)};
waitUntil {player==player};
switch (side player) do
{
case WEST:
{
};
case EAST:
{
};
case RESISTANCE:
{
};
case CIVILIAN:
{
player createDiaryRecord ["Diary",["Missão","
<br/>
_Precisamos passar pelas cidades de Shakhovka e Polana para resgatar o maior número possível de sobreviventes e evacuá-los até Msta.
<br/>
<br/>
_Também precisamos descobrir com o que estamos lidando, se são terroristas ou uma possível invasão.
<br/>
<br/>
_Após investigarmos as vilas e evacuarmos os sobreviventes (se houver), é muito importante que voltemos ao posto avançado para entregar aos cientistas 
tudo que descobrimos sobre os responsáveis ou qualquer anormalidade encontrada no local.
<br/>
<br/>
Objetivo Opcional:
<br/>
<br/>
_Descobrir o paradeiro da equipe policial local que atualmente ainda se encontra desaparecida.
"]];
player createDiaryRecord ["Diary",["Situação","
<br/>
Comandante da Swat:
<br/>
<br/>
_ Senhores, temos hoje uma missão bem diferente do que estamos acostumados e complicada em nossas mãos. Vocês já devem saber do ocorrido então vou poupa-los dos detalhes.
<br/>
<br/>
_ A polícia local já havia enviado algumas unidades para fazer esse trabalho mas pelas informações que me passaram o departamento de polícia perdeu o contato da equipe
há mais de 1 hora atrás, então restou para nós cumprir esta missão.
<br/>
<br/>
_ Após todos vocês serem imaculados com várias doses de vacina contra radiação, nosso objetivo é ir primeiramente em direção à Oeste, para a cidade de Shakhovka e por fim, 
Polana ao Norte para resgatar todos os sobreviventes possíveis destas duas cidades e evacuá-los para o campo de refugiados mais próximo, que atualmente se encontra em Msta.
<br/>
<br/>
_ Ao mesmo tempo, é nosso dever descobrir com o que estamos lidando, se são terroristas ou uma possível invasão. Devemos levar toda a informação e evidências possíveis para
a equipe de ciências do nosso posto avançado, aqui em Solnichniy.
<br/>
<br/>
_ Ahh e eu quase já ia me esquecendo, deixarei na mão de vocês a decisão de descobrir o paradeiro desses incompetentes da polícia local, mas fiquem cientes que se houver
sobreviventes nas cidades a vida deles correm perigo e qualquer demora para dar-lhes assistência médica pode ser fatal. Boa sorte senhores!
<br/>
"]];
player createDiaryRecord ["Diary",["Contexto","
<br/>
16 de Julho de 1989, 23:00 horas.
<br/>
<br/>
Há exatamente às 19:52 dessa noite, uma bomba explodiu perto do centro de Chernarus. Postes de iluminação da cidade e todos os equipamentos eletrônicos por perto foram
destruídos, assim como, a maior parte dos motores dos automóveis do local.
<br/>
<br/>
Dessa bomba foi confirmado a liberação de altas taxas de radiação no local e muito provavelmente as cidades mais próximas a explosão, que no caso, foram Polana e Shakhovka,
não tiveram sobreviventes, se tiveram, não sobreviverão por muito tempo sem ajuda médica. 
<br/>
<br/>
Não podemos confirmar com o que estamos lidando, mas esperamos que seja um ataque terrorista, ou até mesmo no pior das hipóteses, o que vimos é o prenúncio de uma invasão.
<br/>
<br/>
A polícia local das cidades vizinhas foi orientada a evacuar toda a população para a costa e extremidades Sul e Norte de Chernarus no objetivo de proteger os civis da crescente nuvem de 
radiação mortal da bomba.
<br/>
Uma unidade de patrulha policial que estava próximo aos arredores foi designada para montar um campo de refugiados temporário na região de Msta (que por muita sorte não foi atingida pela explosão), 
antes de evacuar toda a população para o Sul, com o objetivo de resgatar os poucos sobreviventes que restaram da cidade de Polana, ao Norte e Shakhovka, a Oeste.
<br/>
<br/>
Para descobrir com o que estamos lidando e assim como, resgatar todos os sobreviventes restantes das cidades vizinhas, uma unidade da SWAT foi designada para tal função.
<br/>
"]];
MAG_tskObj0=player createSimpleTask ["Investigue as Vilas"];
MAG_tskObj0 setSimpleTaskDescription ["Resgate os sobreviventes e descubra com o que estamos lidando.","Resgate e Investigue","Resgate e Investigue"];
};
};
